spring:
  application:
    name: greeting-microservice
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'

greeting-microservice:
  greeting: "Hello"
  default-value: "Gatinhes"